// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'connection': string;
  'message': string;
  'messages_block': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
